### PR TITLE
Auto-open login link

### PR DESCRIPTION
**Pull request by vadi2**
#### Brief overview of PR changes/additions
Added MidMUD.xml file - this is untemplated with my changes in it. If you send Mudlet the XML, it'll take the package name from the file name (unless you give it [a zip](https://wiki.mudlet.org/w/Mudlet_Packages#How_to_create_a_Mudlet_package)) - so having a package called "mudlet" for a Mudlet user doesn't make sense. I understand you'll need to customise this per-game somehow.

Removed a few levels of empty folders.

Added a login trigger to auto-open the page where you can copy the key from.

### CODE REVIEW

**Comment by oestrich** [comment]
I hand merged these in ba8d434. It's definitely awkward since I want to have this customized per game. Does the Mudlet use the URL for anything?

**Comment by vadi2** [comment]
Which url?

**Comment by oestrich** [comment]
ExVenture sends `http://myhost/clients/mudlet.xml` as the URL to fetch the package from. Is `mudlet.xml` used for anything? I figured the package name in the XML would be used.

**Comment by vadi2** [comment]
Ah - if it's an XML file, the file name is used as the package name. If
it's a zip file, the config.lua inside it is read for the package name.

**Comment by vadi2** [comment]
Perfect

**Pull request closed without merging**
