### PR TITLE
Dynamic Damage types

### PR DESCRIPTION
**Pull request by oestrich**
Create custom damage types, don't have a static list. This lets admins create damage types of whatever name they want and determine which stats boosts it and how much.

### CODE REVIEW

**Comment by tielur** [comment]
👏

**Comment by oestrich** [comment]
[Create dynamic damage types](https://trello.com/c/abLBSyur/53-create-dynamic-damage-types)

**Comment by oestrich** [comment]
[Damage types should have an "opposite" stat](https://trello.com/c/Atjj5Iy9/113-damage-types-should-have-an-opposite-stat)

**Comment by oestrich** [comment]
[Damage types should have an "opposite" stat](https://trello.com/c/Atjj5Iy9/113-damage-types-should-have-an-opposite-stat)

**Pull request merged**
