### PR TITLE
Use command should have a target

### PR DESCRIPTION
**Pull request by paulsullivanjr**
Use command should have a target

### CODE REVIEW

**Comment by oestrich** [comment]
For #133 (starting to migrate stuff into github issues instead of trello)

**Comment by oestrich** [comment]
I've been thinking on this, and I think before merging `use` should also take a target in the command itself similar to how skills work. It might be a little weird, but I think the `greet` command could be used to get an idea on how to make it work (you can do `greet town crier hello` and it works.)

So we would want `use bandit poison potion`. I think this is the more likely use case of use having a target? Since you'd probably want `use potion` to default to you, and be required to type out using on another target.

**Comment by paulsullivanjr** [comment]
> I've been thinking on this, and I think before merging `use` should also take a target in the command itself similar to how skills work. It might be a little weird, but I think the `greet` command could be used to get an idea on how to make it work (you can do `greet town crier hello` and it works.)
> 
> So we would want `use bandit poison potion`. I think this is the more likely use case of use having a target? Since you'd probably want `use potion` to default to you, and be required to type out using on another target.

That makes sense. I'll start looking into it. I'll let you know if I run into any issues or have any questions.

**Comment by oestrich** [comment]
Closing due to restarting ExVenture

**Pull request closed without merging**
